### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by dbaeumer** [donaldpipowitch/how-to-create-a-language-server-and-vscode-extension#1]
I have read your post about how to create a language server and I would like to provide some feedback from the point of a VS Code and LSP developer.

I like the post and I highly appreciate the time and effort you put into it. I only found some minor things I would like you to correct:

- vsce does offer a way to list all files that will be packaged upfront. The command is `vsce ls`
- Since you core library offers cancellation support I would suggest you wire that support to LSP cancellation as well. Each handler you register with a connection on the server side takes as a last optional argument a cancellation token.  You can react to cancellation by either polling `isCancellationRequested` or hooking on `onCancellationRequested`. This ensures that all cancellation requests send by VS Code will cancel your request. And usually VS Code for example send a cancel if a user closed the code complete. So there would be no extra work for you.
- Using a document selector for a single file works for me in my test bed. I used `{ pattern: '**/.vscode/test.txt', scheme: 'file' }` which only syncs that single file. can you check if this works as expected if you add the `scheme` property as well.

**Comment by donaldpipowitch** [comment]
Hi @dbaeumer,

this is awesome feedback. Thank you so much for taking the time to read my article and write me.

I'm currently in the middle of updating my Rust tutorial for "Rust 2018" and definitely want to come back to this one after that. I'll add your recommendations and hopefully a couple more features.

**Comment by octref** [comment]
Thanks for writing the tutorial! I think it'll help people who are getting started with LSP development, but here are a few suggestions:

- Don't rely on the unstable marketplace API. For sample purpose I'd choose something like GitHub API (maybe completing github depdendencies in package.json file?)
- For the publishing part, I think it's better to just refer to the official doc instead of repeating its content.
- I wouldn't encourage publishing the packages / extension to the market place.

**Comment by donaldpipowitch** [comment]
> * vsce does offer a way to list all files that will be packaged upfront. The command is `vsce ls`

@dbaeumer , I just tried to run this inside `packages/client` and it errored: ` ERROR  You should not depend on 'vscode' in your 'dependencies'. Did you mean to add it to 'devDependencies'?` Good to know 👍 I'll change that as well. But I guess I need to move my `"postinstall": "vscode-install"` as well, right? Because it would be called when I install my extension, but `vscode-install` isn't available? Or is it callable inside VS Code? (**Update**: Nope, it looks like the examples use this as well in this way: https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-log-streaming-sample. `vscode` is inside `devDependencies`, but `"postinstall": "vscode-install"` is set.)

**Comment by donaldpipowitch** [comment]
Hi @octref,

thank you for the feedback.

> * Don't rely on the unstable marketplace API. For sample purpose I'd choose something like GitHub API (maybe completing github depdendencies in package.json file?)

I wanted to create an extension for a missing feature I'd personally like to see, so I used the unstable Marketplace API. I personally think it is _okay_ to use it for the scope of this tutorial and it's mentioned that it can break at any time. (I actually wrote the Marketplace support about this tutorial as well.)

> * For the publishing part, I think it's better to just refer to the official doc instead of repeating its content.

The official docs (https://code.visualstudio.com/api/working-with-extensions/publishing-extension) are linked in this section. As I said in the introduction: `There are already existing tutorials which cover this topic. ...  sometimes it helps to get a similar tutorial for the same topic from a different perspective. For example my tooling, my project structure and my writing style will be slightly different.`

It's fine from my perspective and it helped me.

> * I wouldn't encourage publishing the packages / extension to the market place.

Do you mean _I_ shouldn't publish it or the people who follow the tutorial? If you want I can add a section where I ask them to _not_ publish duplicates to my extension. But I _had_ to publish my extension to verify everything works correctly.

**Comment by octref** [comment]
Thanks for your response! Yes I wouldn't encourage readers to publish the package so the marketplace get a bunch of "LSP Hello World" extensions relying on an unstable API. Maybe you can add a warning, or add a step that suggests readers to unpublish the extensions once they are done.

**Comment by donaldpipowitch** [comment]
I'll add a warning. You are right that no one benefits from duplicates, if a reader follows the tutorial too closely.

**Comment by dbaeumer** [comment]
@donaldpipowitch yes, vscode should be a dev dependencies since you only needs it during development. We added this warning lately since a lot of extensions (even once we authored) make that mistake :-)

**Comment by donaldpipowitch** [comment]
@dbaeumer Regarding `onCancellationRequested` - would that be the correct way to do it? Do I still need to handle cancelation on my own on frequent `onCompletion` calls or takes VS Code care of calling `onCancellationRequested`, if code completion is requested again and there is still a running search request?

https://github.com/donaldpipowitch/how-to-create-a-language-server-and-vscode-extension/blob/84c23d823024d0324ac3ab78d6a8d6251da8af21/packages/server/src/completion.ts#L29

```diff
-  connection.onCompletion(async ({ position, textDocument }) => {
+  connection.onCompletion(async ({ position, textDocument }, token) => {
+    token.onCancellationRequested(() => {
+      if (lastCancel) {
+        lastCancel();
+        lastCancel = null;
+      }
+    });

    if (lastCancel) {
-     lastCancel(); // is this correct? or should I keep this as well
      lastCancel = null;
    }
    
    // old code...
  });
```

**Comment by dbaeumer** [comment]
@donaldpipowitch VS Code send a cancel event if a code complete request is not valid anymore. However other clients might not. So for safety reasons I would keep both code passes and a comment why they are there.

**Comment by donaldpipowitch** [comment]
Thank you again for the feedback.
